# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       sdk-webapp

# >> macros
# << macros

Summary:    Mer SDK manager
Version:    0.1
Release:    2
Group:      Development/Languages/Ruby
License:    GPLv2+
Source0:    sdk-webapp.tar.bz2
Source100:  sdk-webapp.yaml
Requires:   sdk-webapp-bundle

%description
Allows web-based management of the Mer SDK. Adds toolchains, targets etc


%prep
%setup -q -n src

# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
%{_libdir}/%{name}-bundle/
# >> files
# << files
